"""add_job_meta_field

Revision ID: 684a5e546314
Revises: bb249ed79907
Create Date: 2023-01-18 13:38:07.692830

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "684a5e546314"
down_revision = "bb249ed79907"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("meta", sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "meta")
    # ### end Alembic commands ###
