version: "3.8"
name: whisperbox-transcribe

services:
  traefik:
    image: "traefik:latest"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - web
    networks:
      - traefik

  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - app
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: whisperbox
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data:/var/lib/rabbitmq/mnesia/

  worker:
    env_file: .env
    build:
      context: .
      dockerfile: worker.Dockerfile
      args:
        WHISPER_MODEL: ${WHISPER_MODEL}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app

  web:
    env_file: .env
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app
      - traefik

networks:
  app:
    driver: bridge
  traefik:
    driver: bridge
