version: "3.8"

services:
  traefik:
    container_name: whisperbox-transcribe_traefik

  redis:
    container_name: whisperbox-transcribe_redis

  worker:
    container_name: whisperbox-transcribe_worker
    env_file: .env
    # <GPU SUPPORT>
    # build:
    #   dockerfile: worker.gpu.Dockerfile
    volumes:
      - whisperbox-transcribe-data:/etc/whisperbox-transcribe/data
    # <GPU SUPPORT>
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  web:
    container_name: whisperbox-transcribe_web
    env_file: .env
    volumes:
      - whisperbox-transcribe-data:/etc/whisperbox-transcribe/data
    labels:
      - "traefik.http.routers.web.entrypoints=web"

volumes:
  whisperbox-transcribe-data:
