version: "3.8"

services:
  traefik:
    container_name: whisperbox-transcribe_traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=whisperbox-transcribe_traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_SSLEMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  redis:
    container_name: whisperbox-transcribe_redis

  worker:
    container_name: whisperbox-transcribe_worker
    env_file: .env
    # <GPU SUPPORT>
    # build:
    #   dockerfile: worker.gpu.Dockerfile
    volumes:
      - whisperbox-transcribe-data:/etc/whisperbox-transcribe/data
    # <GPU SUPPORT>
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  web:
    container_name: whisperbox-transcribe_web
    env_file: .env
    volumes:
      - whisperbox-transcribe-data:/etc/whisperbox-transcribe/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
      - "traefik.http.routers.web.rule=(Host(`${TRAEFIK_DOMAIN}`))"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=le"

volumes:
  whisperbox-transcribe-data:
