[project]
name = "whisperbox_transcription"
description = ""
version = "0.0.1"

dependencies=[
  "celery[redis] ==5.2.7",
  "sqlalchemy[mypy] ==1.4.46",
  "pydantic ==1.10.5"
]

[project.optional-dependencies]
web=[
  "alembic ==1.9.4",
  "fastapi ==0.92.0",
  "uvicorn[standard] ==0.20.0",
  "gunicorn ==20.1.0"
]

worker=[
  "whisper-openai ==1.0.0",
  "requests ==2.28.2"
]

tooling = [
  # code formatting
  "black ==23.1.0",
  "isort ==5.12.0",
  # linting
  "flake8 ==6.0.0",
  # tests
  "httpx",
  "sqlalchemy-utils ==0.40.0",
  "python-dotenv ==1.0.0",
  "pytest ==7.2.1",
  # types
  "mypy ==1.0.0",
  "sqlalchemy-stubs ==0.4",
  "types-requests ==2.28.11.15"
]

worker_dev = [
  "watchdog[watchmedo] ==2.3.1"
]

[tool.isort]
profile = "black"

[tool.setuptools]
py-modules = []
