[project]
name = "whisper-api"
description = ""
version = "0.0.1"

dependencies=[
  "celery[redis] ==5.2.7",
  "psycopg2 ==2.9.5",
  "sqlalchemy[mypy] == 1.4.45",
  "python-dotenv ==0.21.0",
]

[project.optional-dependencies]
web=[
  "alembic ==1.9.0",
  "fastapi ==0.88.0",
  "uvicorn[standard] ==0.20.0"
]

worker=[
  "whisper-openai ==1.0.0"
]

dev = [
  # code formatting
  "black",
  "isort",
  # linting
  "flake8",
  "mypy",
]

test = [
  "httpx",
  "sqlalchemy-stubs",
  "sqlalchemy-utils",
  "pytest"
]

[tool.isort]
profile = "black"

[tool.setuptools]
py-modules = []
