[project]
name = "whisperbox-transcribe"
description = ""
version = "0.1.0"

dependencies=[
  "celery[redis] ==5.2.7",
  "sqlalchemy[mypy] ==2.0.17",
  "pydantic ==1.10.9"
]

[project.optional-dependencies]
web=[
  "alembic ==1.11.1",
  "fastapi ==0.92.0",
  "uvicorn[standard] ==0.20.0",
  "gunicorn ==20.1.0"
]

worker=[
  "watchdog[watchmedo] ==2.3.1",
  "whisper-openai ==1.0.0",
  "requests ==2.28.2"
]

tooling = [
  # code formatting
  "black ==23.3.0",
  "isort ==5.12.0",
  # linting
  "flake8 ==6.0.0",
  # tests
  "httpx",
  "sqlalchemy-utils ==0.40.0",
  "python-dotenv ==1.0.0",
  "pytest ==7.3.1",
  # types
  "mypy ==1.0.1",
  "types-requests ==2.28.11.15"
]

[tool.isort]
profile = "black"

[tool.setuptools]
py-modules = []
